config/routes.rb
Balances::Application.routes.draw do

  root to: 'static#root'
  get :home, controller: :static
  get :teaser, controller: :static
  get :terms_privacy, controller: :static
  get :import_instructions, controller: :static
  get '/buy_bitcoins' => redirect("https://coinbase.com/?r=#{ENV['COINBASE_BUY_REFERRAL_ID']}&utm_campaign=user-referral&src=referral-link")


  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: 'admin/letter_opener'
  end

  resources :addresses, only: [:index, :show, :create, :update, :destroy] do
    post :import, on: :collection
    get :detect_currency, on: :collection
    get :info, on: :collection
  end

  resources :announcements, only: [:index] do
    put :mark_as_read
  end

  namespace :coinbase do
    get :auth
    get :callback
  end

  get :transactions, to: 'transactions#index'

  devise_for :users, controllers: { registrations: 'registrations' }
  devise_scope :user do |variable|
    get :settings, to: 'registrations#edit' # We are using a custom controller
    get :sign_in, to: 'devise/sessions#new'
    get :sign_up, to: 'registrations#new' # We are using a custom controller
    delete :sign_out, to: 'devise/sessions#destroy'
  end

  resources :users, only: [:index, :show, :update] do
    post :disable_twofactor, on: :collection
    post :enable_twofactor, on: :collection
    get :twofactor_qr, on: :collection
    get :twofactor_verify, on: :collection
    get 'unsubscribe/:email_hash', on: :collection, action: :unsubscribe, as: :unsubscribe
    get 'unsubscribe/:email_hash/confirm', on: :collection, action: :unsubscribe_confirm, as: :unsubscribe_confirm
  end

  get :admin, to: 'admin#index'
  namespace :admin do
    get :stats
    resources :announcements
  end

  namespace :api do
    namespace :rest do
      namespace :v1 do
        resources :addresses, only: [:create]
        resources :registrations, only: [:create] do
          post :sign_in, on: :collection
          delete :sign_out, on: :collection
        end
        resources :tokens, only: [:create]
      end
    end
  end

end

app/models/announcement.rb
class Announcement < ActiveRecord::Base

  validates_presence_of :content

  has_many :user_read_announcements, dependent: :destroy

  before_save :clean_attributes

  private

  def clean_attributes
    self.content.strip! if self.content.present?
  end

end

app/controllers/admin/announcements_controller.rb
class Admin::AnnouncementsController < AdminController

  def new
    @announcement = Announcement.new
  end

  def edit
    @announcement = Announcement.find(params[:id])
  end

  def create
    @announcement = Announcement.new announcement_params

    if @announcement.save
      redirect_to admin_announcements_path, notice: 'Announcement was created.'
    else
      render :new
    end
  end

  def update
    @announcement = Announcement.find(params[:id])

    if @announcement.update_attributes announcement_params
      redirect_to admin_announcements_path, notice: 'The announcement was updated.'
    else
      render :edit
    end
  end

  def destroy
    @announcement = Announcement.find(params[:id])
    @announcement.destroy

    redirect_to admin_announcements_path, notice: 'The announcement was deleted.'
  end

  private

  def announcement_params
    params.require(:announcement).permit(:content)
  end

end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController

  respond_to :json

  def index
    @announcements = Announcement.where("""
      NOT EXISTS (
        SELECT user_id
        FROM user_read_announcements
        WHERE
          user_id = ? AND
          announcement_id = announcements.id
      )
    """, current_user.id).order('created_at DESC')

    respond_with @announcements
  end

  def mark_as_read
    if Announcement.exists?(params[:announcement_id])
      current_user.user_read_announcements.create(announcement_id: params[:announcement_id])
      render json: {success: {message: 'Announcement marked as read.'}}, status: :ok
    else
      render json: {error: {message: 'Announcement not found.'}}, status: :not_found
    end
  end

end

app/views/admin/announcements/_form.html.haml
= simple_form_for announcement, url: url do |form|
  = form.input :content
  = form.button :submit

app/views/admin/announcements/edit.html.haml
- content_for :title do
  Edit Announcement - Admin Portal

%section
  %article
    %h1 Edit Announcement - Admin Portal
    = render 'form', announcement: @announcement, url: admin_announcement_path

app/views/admin/announcements/index.html.haml
- content_for :title do
  Announcements - Admin Portal

%section
  %article
    %h1 Announcements - Admin Portal

    = render 'shared/flashes'

    %a.button.small.brand{href: new_admin_announcement_path} Create
    %br
    %br

    %table
      %thead
        %tr
          %th Created At
          %th Content
          %th Actions
      %tbody
        - if Announcement.any?
          - Announcement.order('created_at DESC').each do |announcement|
            %tr
              %td= announcement.created_at
              %td= announcement.content
              %td
                %a{href: edit_admin_announcement_path(announcement)} Edit
                |
                = link_to 'Delete',
                  admin_announcement_path(announcement), method: :delete,
                  confirm: 'Are you sure you want to delete this announcement?'
        - else
          %tr
            %td{colspan: 3} No announcements have been made yet.

app/views/admin/announcements/new.html.haml
- content_for :title do
  New Announcement - Admin Portal

%section
  %article
    %h1 New Announcement - Admin Portal
    = render 'form', announcement: @announcement, url: admin_announcements_path